stages:
  - build
  - test

build_image:
  stage: build
  script:
    - docker build -t couchdiscover .

test_couchdiscover:
  stage: test
  script:
    - docker run --rm -v ${PWD}:/project couchdiscover sh -c "cd project && pip install -r requirements.txt && nosetests tests"

after_script:
  - docker rmi couchdiscover
