addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "UDlZmfzI4fevNXgbNRmCIqOwlaaWVO4Zrq7X8M6CV25AEzxjBQ/+rSiHaCZ8MAbvA/no1V2yzqMCPw8+8CKdENXhKym4447JSe2FoZni/ghRAOvc3GRyfD349l42HVxdHq/d1TIXWrIO189felfYcvvXId2usNNn905rXGyFXD89K7XId1ggDZHbr/nP8gzrfoaRDMmW2LbX5omrBatngbEyIpx9h1eXRdAbfYt5cACeglWpYQ+BRsPLGkPjl/2g84ev8vefWHMFCE0VFiX3JNf3/pyjCjb7pB2U91MDTUKRbUGUV12o3RnuxTvRLzFvxdpwDEUA3b7ir5N80esU3Jvcw6gClHuzh07yLceHb40zaq6prduRq2E50NdkcChozIjLQBrNdnUrJzJTHS08oqBqx96ScXm2CYiYZ4nyN5f1JijbZzv7geAdddjJo5EdGZQdMoUknmtJiTw+ikp1sSF4M3OB/rxXw7COD5NGxnMaT9jA7tdbmtNOr01Mf2D6nGPZMK4rQTPxrAUSRcrYklNWYsctiQ67IIm+5X7rTsqAh5OW6WdtthYzAh8N7p9g+xvPmaJaghJ8wpEO864+mhAAdYIK/eH/XEVvr/4pJkoSrrSWaA/+syO7uaSHJxh4o7OuVNPJ80YsYXRxxbCzQPcM9aBWDYKIbdC6Es3VsFE="

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: true

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "wxboT4pw7iJ6BK0bEIGdLufY1W2EXkBK+1XBKob5QT5bVjPAdtiCGEMQjp0SCmhfieIDs7Kqxma6xU/TyajiHXWZrIbu73ecnAN6202xW+WtiZmbQNrbWo85c3mNPELIJ2eZNwYNtLNeDaVOz0rxj7cufD5gcHzwSOkfOfJoiAobjrJ769A8zkcuZro7mEgwgLcrOGyjstny3ryK4+PJkSU1yjyjybOgBzC1Pj1w1y4RfcY3ZvmG0Jqo7C9BBTLVonw0OQsKI1yTGCm4b8V2DEZf4loEAhVNESv8HftGS12DKX9XLNVv5pi7jXpdl9lJO9z8vO8RIJVIpGQagj3AqVIDyeFFx27O55xvvEvIx2Nf70N1wdJ26es1ZTBS1QZm2yXdNR5lBmdtCtbgEApLidoYOdeCkxu65bYfbhGCsTdlwxYy0C+NNn6Gvr19esmsHHWqFjKYoFvSRP9yYiVXinTvRYNpkbKZi9TCKkYuf/1O+bM/EbzAFNOfGiEh/K/G+bRkbEvmPGn5GbOGpifmctafY2C/qN4LYmBnkyvFmDhJjFKerxPg0KJmO5NxaznDp0sg+NLuhHWwao3vlK0zV9LDIZKviW9euCTD/G86y0HnXe7uVOjPTJoxNGVCN9SRRLNzg06Uqp37mHZ0ktHOr6XqLGp90aZB2FzOUyHy7I0="
  on:
    tags: true
  skip_cleanup: true

after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme