addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "T43Ze4D95kERUjmq0mlg8w0J3pFNh/eQoWErlqJ+DLMIYboFnN40guSqJIqye5XWcmTrtt0avZc9R1BQeDWPSeQvEMjHdORgS+bSUD/b8YH7m9mQL67y0n6NhnKK7QhAomlbD7CeJLUNri+IBviH/PMx1yw1M9IDEHK64wxysyzWLjY2OLgcUL3lTefoiNFhVTJs/e4A3qcfYHGYlVmzWXrVjqubfPOBN+k6xFf/kvSNhI/vY0ORQNz7yKx1n8qHq804KjDhbWcxU3MfLm8iXrn4qkMFJI+PT4KW6EJ3/PSYlmla0pO9JLJxM+vzxpkCc2YNyvpOO3XLhjd0/hpemBId+oShiKL7mFeGYqgccGo1gx+Mm1Hh3WE7gYqUxP0SQgXHTBsBF5bzKZshCVZEF/Qr0ZS8qzxJPakX7FHj/K6868MS2pZM2M93XgGzYXCwhSPl3FT1kIksBmm6Zcpk0rlV3zhXY+4H9MpjvF63QWNdlzZrRkjNTQ5v9nEOcsOjHcPVNVk/4wiTfh/pbEkxqrt7Ig15wV1Aqu8VI1S9Ze8As3AGcImAdZrGWCE5ZOJzObYtwCaP6PYYW0PPcaz+YvoOVz1KAPhCZniYXVVYFabR7Yiv1imboFizfXWtS/yOYe6iDBU4+tlT0hKffoQCKI3cUT7anVkLcHI9NpK0vuc="

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: true

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "gixoi+98MrYdjQ4an4AK8ZSIJq3z6Ccisoa4xuIHVxh6/K27g8fs3brpdPVS0sc6pXQgHS5lbxgIX/9k0uOyJbiDsQKNzCpEsdgCUDCEhzDmBoBslJZQq9uy0rGNmYfmfRz2agSj+aYqZzPCcUz/rczCjRZq0zNOr0ELjw3SiZjTXBDrvsp6h+wNpfoez2IgJwXhX19wvBf/X/JKEBoP4yi9yxgYMK8567ADAh/5PFNDU+oe4mam/RZI5MOphN06HL1AhS6OfZuk6oiw6+sow0moUEu58ii+OmrZZnOTmNmWvxHcr0qNuKQVQq3T4OjuhLkmZu0xFFJsHE6dSzdqPo3Vz2ctoFkOA7z9IYQV1RX5nThcXgCam4p4LCrWto212anSjGAjuwdCnp1pMlk1eVGRGQhAm03FcJB62ZgbRtsyMXQahUipDJIFzrVP4dISkDXskk1ftGHV8c/0Xwj++YVYmzqyRNmo8Cng2TiNfQT/5LFKJBhJj/58Pfdg4amXJvQ+kBwzgWlsuQNDr5/Aw9dK7fFDSWjgMxUH+n6b8BEtn2+gBBLUtGOcCgX7H+nAhYCNoPWZIAuAfmJSIHKgbYdjVYFYSr6+HjbSZ3aUJzHcbVwZNbfPDNzohYWac47TZ0Cvic/kB4nlKeOYNg3x0pqx3BMoAi40rAGNsY7ffBk="

  on:
    tags: true
  skip_cleanup: true

after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme